#!/bin/bash

# List files in the current directory in long format
echo "Files in the current directory:"
ls -la

# List files in the parent directory of the current working directory
echo "Files in the parent directory:"
ls -la ..

# List files in the /boot directory
echo "Files in the /boot directory:"
ls -la /boot
